import React, { useState } from 'react';
import { 
  Gamepad2, 
  Sparkles, 
  FileCode2, 
  Layers, 
  ListTodo, 
  ExternalLink, 
  Play, 
  Plus
} from 'lucide-react';

export const AppWalletPlayView: React.FC = () => {
  const [activeLab, setActiveLab] = useState<'spec_builder' | 'dependency_mapper' | 'backlog_estimator' | 'deploy_linker'>('spec_builder');

  // Lab 1: AI SRS Spec Builder Simulator
  const [ideaInput, setIdeaInput] = useState<string>('Hệ thống quản lý kho sách cá nhân thông minh kết hợp OCR quét bìa sách');
  const [engineTier, setEngineTier] = useState<'gemini' | 'gpt4o' | 'heuristic'>('gemini');
  const [generatedSpec, setGeneratedSpec] = useState<string>('');

  const runGenerateSpec = (idea: string, tier: 'gemini' | 'gpt4o' | 'heuristic') => {
    const slug = idea.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 24);
    const engineLabel = tier === 'gemini' ? 'Google Gemini 2.5 Flash' : tier === 'gpt4o' ? 'OpenAI GPT-4o-mini' : 'Offline Heuristic Engine';

    return `# SOFTWARE REQUIREMENTS SPECIFICATION (SRS)
*Generated by ${engineLabel} (Dual-Engine Resilient AI)*

## 1. Executive Summary & Value Proposition
- **Project Name:** ${idea}
- **App Slug:** \`${slug}\`
- **Core Value:** Tối ưu hóa quy trình quản lý thông tin với độ trễ tối thiểu và tính sẵn sàng cao.

## 2. User Personas & Target Audience
- **Kỹ sư / Lập trình viên:** Cần tra cứu nhanh và tương tác thông qua API/CLI.
- **Người dùng cá nhân:** Giao diện tối giản, trực quan, hỗ trợ thiết bị di động.

## 3. Core Feature Specifications (User Stories)
- **US-01 [Ghi nhận]:** Given ý tưởng mới -> When nhập vào hệ thống -> Then tự động sinh siêu dữ liệu.
- **US-02 [Đồng bộ]:** Given có thay đổi -> When bấm Sync -> Then cập nhật trạng thái lên Supabase PostgreSQL.

## 4. Recommended Modern Tech Stack
- **Frontend:** React 19 + TypeScript + Vite + Tailwind CSS
- **Database & Auth:** Supabase PostgreSQL 16+ with Row Level Security (RLS)
- **Deployment:** Vercel Edge Network

## 5. PostgreSQL Database Schema
\`\`\`sql
CREATE TABLE tkw_${slug.replace(/-/g, '_')}_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT now()
);
\`\`\`

## 6. API Contracts & Endpoints
- \`POST /api/v1/items\` — Tạo bản ghi mới kèm payload JSON.
- \`GET /api/v1/items/:id\` — Truy vấn chi tiết bản ghi.

## 7. Security & Row Level Security (RLS)
\`\`\`sql
ALTER TABLE tkw_${slug.replace(/-/g, '_')}_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Owner isolation" ON tkw_${slug.replace(/-/g, '_')}_items
  FOR ALL USING (auth.uid() = user_id);
\`\`\`

## 8. Phased Implementation Roadmap
- [x] Phase 1: Kiến trúc dữ liệu & Thiết kế UI Minimalist
- [ ] Phase 2: Triển khai CRUD API & RLS Security
- [ ] Phase 3: Tích hợp MCP Server Tool cho AI Coding Agents`;
  };

  // Lab 2: App Tech-Stack & Dependency Mapper
  const SAMPLE_APPS = [
    {
      slug: 'aws-mastery',
      name: 'AWS Cloud Mastery (Tập 5)',
      tech: ['React 19', 'Vite', 'Tailwind CSS', 'Supabase Auth', 'Lucide'],
      sharedDeps: ['Supabase Auth Hub', 'Universal DB MCP'],
      role: 'Domain Mastery'
    },
    {
      slug: 'app-system',
      name: 'Unified-App-Infra (Tập 12)',
      tech: ['PostgreSQL 16', 'Docker', 'Kong API Gateway', 'Redis'],
      sharedDeps: ['Central DB', 'SSO Gateway'],
      role: 'Infra Base'
    },
    {
      slug: 'app-wallet',
      name: 'JohnnyHoang App Wallet (Tập 14)',
      tech: ['React 19', 'Gemini API', 'GPT-4o-mini', 'Supabase RLS'],
      sharedDeps: ['GitHub API', 'Vercel API', 'Supabase Auth Hub'],
      role: 'Orchestrator'
    }
  ];
  const [selectedAppSlug, setSelectedAppSlug] = useState<string>('app-wallet');
  const activeApp = SAMPLE_APPS.find(a => a.slug === selectedAppSlug) || SAMPLE_APPS[0];

  // Lab 3: In-App Backlog Estimator
  const [backlogTitle, setBacklogTitle] = useState<string>('Thêm bộ lọc tìm kiếm theo Tech-Stack');
  const [backlogCat, setBacklogCat] = useState<'feature' | 'bug' | 'refactor' | 'docs'>('feature');
  const [backlogPriority, setBacklogPriority] = useState<'urgent' | 'high' | 'medium' | 'low'>('high');
  const [createdBacklogs, setCreatedBacklogs] = useState<any[]>([
    { id: '1', title: 'Tích hợp MCP Server đọc SRS tự động', cat: 'feature', priority: 'urgent', status: 'todo' },
    { id: '2', title: 'Tối ưu RLS Security Definer function', cat: 'refactor', priority: 'high', status: 'in_progress' }
  ]);

  const handleAddBacklog = () => {
    if (!backlogTitle.trim()) return;
    const newItem = {
      id: Date.now().toString(),
      title: backlogTitle.trim(),
      cat: backlogCat,
      priority: backlogPriority,
      status: 'todo'
    };
    setCreatedBacklogs([newItem, ...createdBacklogs]);
    setBacklogTitle('');
  };

  // Lab 4: Lifecycle & Deployment Linker
  const [projectName, setProjectName] = useState<string>('DevOps Monitor');
  const projectSlug = projectName.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 20);

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 py-10 px-4 sm:px-6">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-8 border-b border-slate-800">
          <div>
            <span className="text-xs font-semibold text-emerald-400 uppercase tracking-widest flex items-center gap-1.5 mb-1">
              <Gamepad2 className="w-3.5 h-3.5" /> Interactive Sandbox & Labs
            </span>
            <h1 className="text-2xl sm:text-3xl font-bold text-white">
              Phòng Thí Nghiệm & Mô Phỏng App Wallet
            </h1>
          </div>
        </div>

        {/* Tab Selection */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mt-6">
          <button
            onClick={() => setActiveLab('spec_builder')}
            className={`p-3 rounded-lg border text-left transition-all ${
              activeLab === 'spec_builder'
                ? 'bg-emerald-500/10 border-emerald-500 text-emerald-300'
                : 'bg-slate-900/60 border-slate-800 text-slate-400 hover:border-slate-700'
            }`}
          >
            <div className="flex items-center gap-2 font-semibold text-xs sm:text-sm mb-1">
              <FileCode2 className="w-4 h-4 text-emerald-400" />
              1. AI SRS Builder
            </div>
            <div className="text-[11px] text-slate-500">Động cơ sinh đặc tả 8 mục</div>
          </button>

          <button
            onClick={() => setActiveLab('dependency_mapper')}
            className={`p-3 rounded-lg border text-left transition-all ${
              activeLab === 'dependency_mapper'
                ? 'bg-emerald-500/10 border-emerald-500 text-emerald-300'
                : 'bg-slate-900/60 border-slate-800 text-slate-400 hover:border-slate-700'
            }`}
          >
            <div className="flex items-center gap-2 font-semibold text-xs sm:text-sm mb-1">
              <Layers className="w-4 h-4 text-emerald-400" />
              2. Dependency Graph
            </div>
            <div className="text-[11px] text-slate-500">Liên kết giữa 17+ apps</div>
          </button>

          <button
            onClick={() => setActiveLab('backlog_estimator')}
            className={`p-3 rounded-lg border text-left transition-all ${
              activeLab === 'backlog_estimator'
                ? 'bg-emerald-500/10 border-emerald-500 text-emerald-300'
                : 'bg-slate-900/60 border-slate-800 text-slate-400 hover:border-slate-700'
            }`}
          >
            <div className="flex items-center gap-2 font-semibold text-xs sm:text-sm mb-1">
              <ListTodo className="w-4 h-4 text-emerald-400" />
              3. In-App Backlog
            </div>
            <div className="text-[11px] text-slate-500">Quản trị việc tinh gọn</div>
          </button>

          <button
            onClick={() => setActiveLab('deploy_linker')}
            className={`p-3 rounded-lg border text-left transition-all ${
              activeLab === 'deploy_linker'
                ? 'bg-emerald-500/10 border-emerald-500 text-emerald-300'
                : 'bg-slate-900/60 border-slate-800 text-slate-400 hover:border-slate-700'
            }`}
          >
            <div className="flex items-center gap-2 font-semibold text-xs sm:text-sm mb-1">
              <ExternalLink className="w-4 h-4 text-emerald-400" />
              4. Dev Linker
            </div>
            <div className="text-[11px] text-slate-500">GitHub & Vercel hub</div>
          </button>
        </div>

        {/* Lab 1: AI Spec Builder */}
        {activeLab === 'spec_builder' && (
          <div className="mt-8 bg-slate-900/80 border border-slate-800 rounded-xl p-6">
            <h3 className="text-base font-bold text-white mb-1 flex items-center gap-2">
              <FileCode2 className="w-4 h-4 text-emerald-400" />
              Mô Phỏng Động Cơ AI App Builder (Dual-Engine Fallback)
            </h3>
            <p className="text-slate-400 text-xs mb-5">
              Nhập ý tưởng và chọn tầng AI engine để xem toàn bộ hồ sơ kỹ thuật 8 phần được sinh ra tức thì.
            </p>

            <div className="space-y-4 mb-6">
              <input
                type="text"
                value={ideaInput}
                onChange={(e) => setIdeaInput(e.target.value)}
                placeholder="Nhập ý tưởng ứng dụng..."
                className="w-full bg-slate-950 border border-slate-800 rounded-lg px-4 py-2.5 text-sm text-slate-100 focus:outline-none focus:border-emerald-500"
              />

              <div className="flex flex-wrap items-center justify-between gap-3">
                <div className="flex items-center gap-2 text-xs">
                  <span className="text-slate-400">Chọn Engine:</span>
                  <button
                    onClick={() => setEngineTier('gemini')}
                    className={`px-3 py-1 rounded-md text-xs font-medium border transition-colors ${
                      engineTier === 'gemini'
                        ? 'bg-emerald-500/20 border-emerald-500/50 text-emerald-300'
                        : 'bg-slate-950 border-slate-800 text-slate-400'
                    }`}
                  >
                    Tier 1: Gemini 2.5 Flash
                  </button>
                  <button
                    onClick={() => setEngineTier('gpt4o')}
                    className={`px-3 py-1 rounded-md text-xs font-medium border transition-colors ${
                      engineTier === 'gpt4o'
                        ? 'bg-emerald-500/20 border-emerald-500/50 text-emerald-300'
                        : 'bg-slate-950 border-slate-800 text-slate-400'
                    }`}
                  >
                    Tier 2: GPT-4o-mini
                  </button>
                  <button
                    onClick={() => setEngineTier('heuristic')}
                    className={`px-3 py-1 rounded-md text-xs font-medium border transition-colors ${
                      engineTier === 'heuristic'
                        ? 'bg-emerald-500/20 border-emerald-500/50 text-emerald-300'
                        : 'bg-slate-950 border-slate-800 text-slate-400'
                    }`}
                  >
                    Tier 3: Offline Heuristic
                  </button>
                </div>

                <button
                  onClick={() => setGeneratedSpec(runGenerateSpec(ideaInput, engineTier))}
                  className="px-4 py-2 bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold rounded-lg text-xs transition-all flex items-center gap-2"
                >
                  <Sparkles className="w-3.5 h-3.5" /> Tạo Hồ Sơ SRS
                </button>
              </div>
            </div>

            {generatedSpec && (
              <div className="p-4 bg-slate-950 rounded-lg border border-slate-800 font-mono text-xs text-slate-300 whitespace-pre-wrap leading-relaxed max-h-96 overflow-y-auto">
                {generatedSpec}
              </div>
            )}
          </div>
        )}

        {/* Lab 2: Dependency Mapper */}
        {activeLab === 'dependency_mapper' && (
          <div className="mt-8 bg-slate-900/80 border border-slate-800 rounded-xl p-6">
            <h3 className="text-base font-bold text-white mb-1 flex items-center gap-2">
              <Layers className="w-4 h-4 text-emerald-400" />
              Sơ Đồ Phụ Thuộc Ứng Dụng (Ecosystem Dependency Graph)
            </h3>
            <p className="text-slate-400 text-xs mb-5">
              Chọn ứng dụng để kiểm tra quan hệ tech-stack và các dịch vụ dùng chung trong hệ sinh thái.
            </p>

            <div className="flex gap-2 mb-6 overflow-x-auto no-scrollbar pb-1">
              {SAMPLE_APPS.map((app) => (
                <button
                  key={app.slug}
                  onClick={() => setSelectedAppSlug(app.slug)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors whitespace-nowrap ${
                    selectedAppSlug === app.slug
                      ? 'bg-emerald-500/15 border-emerald-500/50 text-emerald-300 font-bold'
                      : 'bg-slate-950 border-slate-800 text-slate-400 hover:text-slate-200'
                  }`}
                >
                  {app.name}
                </button>
              ))}
            </div>

            <div className="p-5 bg-slate-950 rounded-lg border border-slate-800 space-y-4">
              <div>
                <span className="text-xs text-slate-500 block mb-1">Vai trò kiến trúc:</span>
                <span className="px-2.5 py-1 bg-slate-900 rounded border border-slate-800 text-xs font-mono text-emerald-400 font-semibold">
                  {activeApp.role}
                </span>
              </div>

              <div>
                <span className="text-xs text-slate-500 block mb-1">Tech Stack:</span>
                <div className="flex flex-wrap gap-1.5">
                  {activeApp.tech.map((t, idx) => (
                    <span key={idx} className="px-2 py-0.5 bg-slate-900 text-slate-300 rounded text-xs border border-slate-800">
                      {t}
                    </span>
                  ))}
                </div>
              </div>

              <div>
                <span className="text-xs text-slate-500 block mb-1">Dịch vụ dùng chung (Shared Dependencies):</span>
                <div className="flex flex-wrap gap-1.5">
                  {activeApp.sharedDeps.map((d, idx) => (
                    <span key={idx} className="px-2 py-0.5 bg-emerald-950/40 text-emerald-300 rounded text-xs border border-emerald-500/30">
                      {d}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Lab 3: In-App Backlog */}
        {activeLab === 'backlog_estimator' && (
          <div className="mt-8 bg-slate-900/80 border border-slate-800 rounded-xl p-6">
            <h3 className="text-base font-bold text-white mb-1 flex items-center gap-2">
              <ListTodo className="w-4 h-4 text-emerald-400" />
              Mô Phỏng In-App Backlog Tracker
            </h3>
            <p className="text-slate-400 text-xs mb-5">
              Tạo và phân loại công việc kỹ thuật ngay trên ứng dụng mà không cần qua Jira/Trello.
            </p>

            <div className="grid grid-cols-1 sm:grid-cols-4 gap-2 mb-6">
              <input
                type="text"
                value={backlogTitle}
                onChange={(e) => setBacklogTitle(e.target.value)}
                placeholder="Tên công việc / bug..."
                className="sm:col-span-2 bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-xs text-slate-100 focus:outline-none focus:border-emerald-500"
              />
              <select
                value={backlogCat}
                onChange={(e) => setBacklogCat(e.target.value as any)}
                className="bg-slate-950 border border-slate-800 rounded-lg px-2 py-2 text-xs text-slate-200"
              >
                <option value="feature">Feature (Tính năng)</option>
                <option value="bug">Bug (Lỗi)</option>
                <option value="refactor">Refactor (Tái cấu trúc)</option>
                <option value="docs">Docs (Tài liệu)</option>
              </select>
              <button
                onClick={handleAddBacklog}
                className="bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold rounded-lg text-xs py-2 px-3 transition-colors flex items-center justify-center gap-1.5"
              >
                <Plus className="w-3.5 h-3.5" /> Thêm Việc
              </button>
            </div>

            <div className="space-y-2">
              {createdBacklogs.map((item) => (
                <div key={item.id} className="p-3 bg-slate-950 rounded-lg border border-slate-800 flex items-center justify-between text-xs">
                  <div className="flex items-center gap-2.5">
                    <span className={`px-2 py-0.5 rounded text-[10px] font-mono uppercase font-semibold ${
                      item.cat === 'bug' ? 'bg-rose-950 text-rose-300 border border-rose-800' :
                      item.cat === 'refactor' ? 'bg-purple-950 text-purple-300 border border-purple-800' :
                      'bg-emerald-950 text-emerald-300 border border-emerald-800'
                    }`}>
                      {item.cat}
                    </span>
                    <span className="text-slate-200">{item.title}</span>
                  </div>
                  <span className="text-slate-500 font-mono text-[10px] uppercase">{item.priority}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Lab 4: Dev Linker */}
        {activeLab === 'deploy_linker' && (
          <div className="mt-8 bg-slate-900/80 border border-slate-800 rounded-xl p-6">
            <h3 className="text-base font-bold text-white mb-1 flex items-center gap-2">
              <ExternalLink className="w-4 h-4 text-emerald-400" />
              Bộ Sinh Siêu Dữ Liệu & Liên Kết Vòng Đời Dev
            </h3>
            <p className="text-slate-400 text-xs mb-5">
              Tự động tạo các liên kết chuẩn hóa cho GitHub, Vercel và Production Domain dựa trên tên dự án.
            </p>

            <div className="mb-6">
              <label className="block text-xs font-semibold text-slate-300 mb-2">
                Tên Dự Án (Project Name):
              </label>
              <input
                type="text"
                value={projectName}
                onChange={(e) => setProjectName(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-lg px-4 py-2 text-xs text-slate-100 focus:outline-none focus:border-emerald-500"
              />
            </div>

            <div className="p-4 bg-slate-950 rounded-lg border border-slate-800 font-mono text-xs space-y-2.5 text-slate-300">
              <div className="flex items-center justify-between border-b border-slate-800 pb-2">
                <span className="text-slate-500">Project Slug:</span>
                <span className="text-emerald-400 font-bold">{projectSlug}</span>
              </div>
              <div className="flex items-center justify-between border-b border-slate-800 pb-2">
                <span className="text-slate-500">Local Path:</span>
                <span className="text-slate-300">D:\Hoa Hoang\Apps\{projectSlug}</span>
              </div>
              <div className="flex items-center justify-between border-b border-slate-800 pb-2">
                <span className="text-slate-500">GitHub Remote:</span>
                <span className="text-sky-400">https://github.com/johnnyhoang/{projectSlug}</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-slate-500">Vercel Production:</span>
                <span className="text-emerald-300">https://{projectSlug}.vercel.app</span>
              </div>
            </div>
          </div>
        )}

      </div>
    </div>
  );
};

export default AppWalletPlayView;
